name: 'Mobile App Publishing'
description: 'Publishes the app to Expo for internal testing'

inputs:
  expo-username:
    description: 'The username for the expo account being published to'
    required: true
  expo-password:
    description: 'The password for the expo account being published to'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Expo login
      uses: expo/expo-github-action@v6
      with:
        expo-version: latest
        username: ${{ inputs.expo-username }}
        password: ${{ inputs.expo-password }}
        timeout-minutes: 5
    - name: Update version number # Set the version number to include the commit hash for internal verification
      run: jq -r --arg VERSION "$(jq -r '.expo.version' < app.json)-$(git rev-parse HEAD | cut -c 1-7)" '.expo.version=$VERSION' < app.json > app2.json && cp app2.json app.json && rm app2.json
      shell: bash
      with: 
        timeout-minutes: 5
    - name: Publish
      run: expo publish
      shell: bash
      with:
        timeout-minutes: 20
